name: storylens
description: 'Capture your story here.'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  google_fonts: 6.2.1
  image_picker: ^1.0.8
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - images/login.png
    - images/register.png
